import Header from "./components/Header";
import "./globals.css";
import localFont from "next/font/local"

const monaco = localFont({
  src: [
    {
      path: "../../public/assets/fonts/monaco/Monaco.ttf",
      weight: "100"
    },
  ],
  variable: "--font-monaco",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monaco.className}>
        {children}
      </body>
    </html>
  );
}
